### ISSUE TITLE
Latest linux merge to master (2.0.16) failed

### ISSUE THREAD

**Issue by parente** [conda-forge/python-hdfs-feedstock#6]
https://anaconda.org/conda-forge/python-hdfs/files

I've restarted it: https://circleci.com/gh/conda-forge/python-hdfs-feedstock/13

Opening this to track that it's still an outstanding issue until the build publishes.

**Comment by parente** [comment]
Hmm. Failed nearly instantly again with a git permission denied error. Will try re-rendering the feedstock next I guess.

**Comment by mariusvniekerk** [comment]
If

**Comment by mariusvniekerk** [comment]
It continues you may want to ping one of the conda forge admins

**Comment by parente** [comment]
Even after re-rendering, it's still failing with the same git permission error.

https://circleci.com/gh/conda-forge/python-hdfs-feedstock/16

@ocefpaf or @jakirkham would you mind taking a look at what's going wrong here when you get a minute?

**Comment by jakirkham** [comment]
Have PMed you about this on gitter @parente.

**Comment by parente** [comment]
Thanks for the hint @jakirkham . Should I submit another dummy PR here to force a build or will the merge to master in staged-recipes somehow trigger a rebuild of master here?

**Comment by jakirkham** [comment]
No need. Will happen once staged-recipes clears it.

**Comment by parente** [comment]
Nothing happening so far https://circleci.com/gh/conda-forge/python-hdfs-feedstock  but I also don't know what to watch or expect after merging in staged-recipes.

**Comment by parente** [comment]
All good now. Thanks again for the help @jakirkham .
